columns:
  evaluator_id:
    - "ID valutatore"
    - "ID Valutatore"
    - "evaluator_id"
    - "Valutatore"
  app:
    - "App analizzata"
    - "App valutata"
    - "app"
    - "system"
  task:
    - "Task analizzata"
    - "Task"
    - "task"
  short_description:
    - "Descrizione breve"
    - "Problema"
    - "short_description"
  long_description:
    - "Descrizione lunga"
    - "Descrizione dettagliata"
    - "long_description"
  heuristic:
    - "Euristica violata"
    - "Euristiche violate"
    - "heuristic"
    - "heuristics"
  severity:
    - "Severita"
    - "Severità"
    - "severity"
  top5:
    - "Problema tra i 5 piu gravi?"
    - "Problema tra i 5 più gravi?"
    - "top5"
    - "Top 5"
