from __future__ import annotations

from ..config import resolve_path
from .asset_export import export_slide_assets


def generate_slide_manifest() -> None:
    assets = export_slide_assets()
    manifest = resolve_path("outputs/slide_manifest.md")
    manifest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Slide Manifest",
        "",
        "## Uso Grafici",
        "- `outputs/figures/clean/`: usare per report e controllo statistico.",
        "- `outputs/figures/presentation/`: usare per slide e Canva/PowerPoint.",
        "",
        "## 1. Introduzione",
        "- Testo: `outputs/text_snippets/intro.md`",
        "- Sezione report: `outputs/generated_report_sections/01_introduzione.md`",
        "",
        "## 2. Valutazione euristica",
        "- Testo: `outputs/text_snippets/heuristics.md`",
        "- Grafici/tabelle: `outputs/slide_assets/02_heuristics/`",
        "- Clean: `outputs/figures/clean/heuristics_heuristics_distribution.png`",
        "- Presentation: `outputs/figures/presentation/heuristics_heuristics_distribution.png`",
        "",
        "## 3. User Test",
        "- Testo: `outputs/text_snippets/user_tests.md`",
        "- Grafici: `outputs/slide_assets/03_user_tests/`",
        "- Clean: `outputs/figures/clean/user_tests_effectiveness_deliveroo_vs_glovo.png`",
        "- Presentation: `outputs/figures/presentation/user_tests_effectiveness_deliveroo_vs_glovo.png`",
        "",
        "## User Test - Tempi, efficacia ed errori",
        "",
        "### Tabelle",
        "- `outputs/tables/users_time_summary.md`",
        "- `outputs/tables/users_time_stat_tests.csv`",
        "",
        "### Grafici",
        "- Clean: `outputs/figures/clean/users_time_mean_by_task.png`",
        "- Presentation: `outputs/figures/presentation/users_time_mean_by_task.png`",
        "- Clean: `outputs/figures/clean/users_time_boxplot_by_task.png`",
        "- Presentation: `outputs/figures/presentation/users_time_boxplot_by_task.png`",
        "- Clean: `outputs/figures/clean/users_time_success_rate.png`",
        "- Presentation: `outputs/figures/presentation/users_time_success_rate.png`",
        "- Clean: `outputs/figures/clean/users_time_errors_by_task.png`",
        "- Presentation: `outputs/figures/presentation/users_time_errors_by_task.png`",
        "",
        "### Testi pronti per slide",
        "- `outputs/text/users_time_interpretation.md`",
        "",
        "## 4. Questionario UEQ e NPS",
        "- Testo: `outputs/text_snippets/questionnaire.md`",
        "- NPS: `outputs/text_snippets/nps.md`",
        "- Grafici: `outputs/slide_assets/04_questionnaire/`",
        "- Clean: `outputs/figures/clean/questionnaire_ueq_scales.png`",
        "- Presentation: `outputs/figures/presentation/questionnaire_ueq_scales.png`",
        "",
        "## 5. Conclusioni",
        "- Testo: `outputs/text_snippets/conclusions.md`",
        "- Sintesi: `outputs/slide_assets/05_conclusions/`",
        "",
        "## Asset copiati",
        *[f"- `{asset}`" for asset in assets],
        "",
        "## Note",
        "- Se un asset non compare, significa che il dato corrispondente manca o non e stato generato.",
        "- Le euristiche importate da Formbricks richiedono review manuale in `data/processed/heuristics_review.csv` prima dell'analisi finale.",
    ]
    manifest.write_text("\n".join(lines), encoding="utf-8")
